### ISSUE TITLE
기본정보

### ISSUE THREAD

**Issue by obov** [ActualProject99/Frontend#4]
- [x] 미니 달력
- [x] 지도

**Comment by rklskhj** [comment]
-[] 미니 달력
-[] 지도

**Comment by rklskhj** [comment]
미니 달력 커스텀 방법 터특!
미니 달력에 시간 제거 했습니다
지도 백엔드 분들과 상의 후 정보 제공 예정
22/11/13 am 2:18 git push 합니다!
